import MobileHeader from '@/components/layout/MoblieHeader'
import '@/styles'
import { mobileOnly } from '@/styles/utils.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => {
    return (
        <html lang='ko' className='trancy-ko'>
            <body>
                <main>
                    <div className={mobileOnly}>
                        <MobileHeader title='공지사항' isBackButton />
                    </div>
                    {children}
                </main>
            </body>
        </html>
    )
}

export default RootLayout
